name: Manual Test Run - File Upload App

on:
  workflow_dispatch:  # Enables manual trigger via GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: file_upload_V2  # Use your custom branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize DB
      run: |
        source venv/bin/activate
        python -c "import db; db.init_db(); print('DB initialized')"

    - name: Run Flask app (test)
      run: |
        source venv/bin/activate
        nohup python app.py &
        sleep 10
        curl -I http://localhost:5000 || echo "App started successfully (test mode)"
